---
azs:
- name: z1
  cloud_properties: {zone: europe-west1-b}
- name: z2
  cloud_properties: {zone: europe-west3-c}
- name: z3
  cloud_properties: {zone: europe-west2-c}

vm_types:
- name: default
  cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 20
    root_disk_type: pd-ssd

disk_types:
- name: default
  disk_size: 3000

networks:
- name: default
  type: dynamic
  subnets:
  - azs:     [z1, z2, z3]
    cloud_properties:
      network_name: default
      ephemeral_external_ip: true
      tags: [internal, concourse]
- name: vip
  type: vip

compilation:
  workers: 3
  reuse_compilation_vms: true
  az: z1
  vm_type: default
  network: default
