---
name: learn-bosh

releases:
- name: learn-bosh
  version: latest

stemcells:
- alias: default
  os: centos-7
  version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
- name: learn_bosh
  azs: [z1, z2, z3]
  instances: 1
  jobs:
  - name: app
    release: learn-bosh
    properties: {}
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  networks:
  - name: default

